using ReportsService.Models;

namespace ReportsService.Services;

public class ReportService
{
    private readonly ILogger<ReportService> _logger;

    public ReportService(ILogger<ReportService> logger)
    {
        _logger = logger;
    }

    public ProjectStatusReport GenerateProjectStatusReport(string projectId)
    {
        _logger.LogInformation("Generating status report for project {ProjectId}", projectId);

        // In production: fetch from database/API
        return new ProjectStatusReport(
            ProjectId: projectId,
            ProjectName: "E-Commerce Platform",
            ClientName: "Acme Corporation",
            Status: "IN_PROGRESS",
            BudgetUtilization: 68.5m,
            TotalTasks: 24,
            CompletedTasks: 14,
            OverdueTasks: 2,
            GeneratedAt: DateTime.UtcNow
        );
    }

    public SprintSummary GenerateSprintSummary(string projectId, int sprintNumber)
    {
        return new SprintSummary(
            ProjectId: projectId,
            SprintNumber: sprintNumber,
            Velocity: 42,
            CompletedPoints: 38,
            CarryOverPoints: 4,
            CompletedStories: ["Auth flow", "DB schema", "CI/CD pipeline", "Dashboard API"],
            StartDate: DateTime.UtcNow.AddDays(-14),
            EndDate: DateTime.UtcNow
        );
    }

    public byte[] GeneratePdfReport(string projectId)
    {
        // In production: use a PDF library like iTextSharp or QuestPDF
        var content = $"Project Status Report\nProject ID: {projectId}\nGenerated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC\n\nThis report is auto-generated by the AI Client Operations Portal.";
        return System.Text.Encoding.UTF8.GetBytes(content);
    }
}
